services:
  interimManager:
    class: InterimBundle\Services\Manager\interimManager
    arguments: ['@doctrine.orm.entity_manager']

  missionManager:
    class: InterimBundle\Services\Manager\missionManager
    arguments: ['@doctrine.orm.entity_manager']
