<?php

namespace InterimBundle\Repository;

/**
 * InterimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterimRepository extends \Doctrine\ORM\EntityRepository
{
}
