<?php

namespace InterimBundle\Repository;

/**
 * MissionMonitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionMonitorRepository extends \Doctrine\ORM\EntityRepository
{
}
